<?xml version="1.0"?>
<robot name="wheels" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:macro name="wheels" params="chassis_width wheelbase">

    <!-- ********** -->
    <!-- Parameters -->
    <!-- ********** -->

    <xacro:property name="degrees_90" value="1.5708"/>

    <xacro:property name="wheel_mass" value="10.0"/>

    <xacro:property name="wheel_diameter" value="0.505"/>
    <xacro:property name="wheel_width" value="0.2"/>

    <xacro:property name="wheel_friction_mu1" value="2"/>
    <xacro:property name="wheel_friction_mu2" value="2"/>
    <xacro:property name="wheel_friction_kp" value="1e8"/>

    <xacro:property name="steering_hinge_mass" value="1"/>

    <!-- ***************** -->
    <!-- Wheel description -->
    <!-- ***************** -->

    <xacro:macro name="wheel"
                 params="lr_prefix fr_prefix">
      <link name="${lr_prefix}_${fr_prefix}_wheel">
        <inertial>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <mass value="${wheel_mass}"/>
          <inertia
              ixx="0.3"
              ixy="0"
              ixz="0"
              iyy="0.2"
              iyz="0"
              izz="0.2"   />
        </inertial>

        <visual>
          <origin xyz="0 0 0" rpy="${degrees_90} 0 0"/>
          <geometry>
            <mesh filename="file://$(find chasing_coins)/meshes/wheel_${lr_prefix}.dae"/>
          </geometry>
          <material name="tire_mat"/>
        </visual>

        <collision>
          <origin xyz="0 0 0" rpy="${degrees_90} 0 0"/>
          <geometry>
            <cylinder radius="${wheel_diameter / 2}" length="${wheel_width}"/>
          </geometry>
        </collision>
      </link>

      <gazebo reference="${lr_prefix}_${fr_prefix}_wheel">
        <material>Gazebo/Black</material>
        <mu1>${wheel_friction_mu1}</mu1>
        <mu2>${wheel_friction_mu2}</mu2>
        <!-- <minDepth>0.005</minDepth> -->
        <kp>${wheel_friction_kp}</kp>
      </gazebo>
    </xacro:macro>

    <!-- ********************************* -->
    <!-- Front and rear wheel descriptions -->
    <!-- ********************************* -->

    <!-- Description of how a front wheel is connected to the chassis -->
    <xacro:macro name="front_wheel"
                 params="lr_prefix lr_reflect">

      <joint name="${lr_prefix}_steering_hinge_joint" type="revolute">
        <origin xyz="${wheelbase / 2}
                     ${lr_reflect * ((chassis_width - wheel_width) / 2)}
                     0"
                rpy="0 0 0"/>
        <parent link="chassis"/>
        <child link="${lr_prefix}_steering_hinge"/>
        <axis xyz="0 0 1"/>
        <limit lower="${config['input_ranges']['steering']['min']}" upper="${config['input_ranges']['steering']['max']}" effort="10000000" velocity="1000000"/>
      </joint>

      <link name="${lr_prefix}_steering_hinge">
        <inertial>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <mass value="${steering_hinge_mass}"/>
          <inertia
              ixx="0.04"
              ixy="0.0"
              ixz="0.0"
              iyy="0.04"
              iyz="0.0"
              izz="0.04"   />
        </inertial>
      </link>

      <joint name="front_${lr_prefix}_wheel_joint" type="continuous">
        <origin xyz="0 0 0"
                rpy="0 0 0"/>
        <parent link="${lr_prefix}_steering_hinge"/>
        <child link="${lr_prefix}_front_wheel"/>
        <axis xyz="0 1 0"/>
        <limit lower="0" upper="0" effort="10000000" velocity="1000000"/>
      </joint>

      <xacro:wheel lr_prefix="${lr_prefix}" fr_prefix="front"/>
    </xacro:macro>

    <!-- Description of how a rear wheel is connected to the chassis -->
    <xacro:macro name="rear_wheel"
                 params="lr_prefix lr_reflect">

      <joint name="rear_${lr_prefix}_wheel_joint" type="continuous">
        <origin xyz="${-1 * wheelbase / 2}
                     ${lr_reflect * ((chassis_width - wheel_width) / 2)}
                     0"
                rpy="0 0 0"/>
        <parent link="chassis"/>
        <child link="${lr_prefix}_rear_wheel"/>
        <axis xyz="0 1 0"/>
        <limit lower="0" upper="0" effort="10000000" velocity="1000000"/>
      </joint>

      <xacro:wheel lr_prefix="${lr_prefix}" fr_prefix="rear"/>
    </xacro:macro>

    <!-- ************** -->
    <!-- Add the wheels -->
    <!-- ************** -->

    <xacro:front_wheel lr_prefix="left" lr_reflect="1"/>
    <xacro:front_wheel lr_prefix="right" lr_reflect="-1"/>

    <xacro:rear_wheel lr_prefix="left" lr_reflect="1" />
    <xacro:rear_wheel lr_prefix="right" lr_reflect="-1" />
    <xacro:property name="PI" value="3.1415926535897931"/>
      <gazebo> 
        <plugin name="gazebo_ros_ackermann_drive" filename="libgazebo_ros_ackermann_drive.so"> 
            <!-- <updateRate>100.0</updateRate>  
            <robotNamespace/>  
            <leftFrontJoint>front_left_wheel_joint</leftFrontJoint>  
            <leftRearJoint>rear_left_wheel_joint</leftRearJoint>  
            <rightFrontJoint>front_right_wheel_joint</rightFrontJoint>  
            <rightRearJoint>rear_right_wheel_joint</rightRearJoint>  
            <wheelSeparation>${chassis_width}</wheelSeparation>  
            <wheelDiameter>${wheel_diameter}</wheelDiameter>  
            <commandTopic>/hrt/cmd_vel</commandTopic>  
            <odometryTopic>odom</odometryTopic>  
            <robotBaseFrame>base_footprint</robotBaseFrame>  
            <odometryFrame>odom</odometryFrame>  
            <torque>1</torque>  
            <topicName>cmd_vel</topicName>  
            <broadcastTF>1</broadcastTF>  -->
            <ros>
                <namespace></namespace>
                <remapping>cmd_vel:=hrt_cmd</remapping>
                <!-- <remapping>odom:=odom_demo</remapping> -->
                <!-- <remapping>distance:=distance_demo</remapping> -->
            </ros>
            <update_rate>100.0</update_rate>
            <front_left_joint>front_left_wheel_joint</front_left_joint>
            <front_right_joint>front_right_wheel_joint</front_right_joint>
            <rear_left_joint>rear_left_wheel_joint</rear_left_joint>
            <rear_right_joint>rear_right_wheel_joint</rear_right_joint>
            <left_steering_joint>left_steering_hinge_joint</left_steering_joint>
            <right_steering_joint>right_steering_hinge_joint</right_steering_joint>
            <!-- <steering_wheel_joint>steering_wheel_joint${name_suffix}</steering_wheel_joint> -->
            <max_steer>${PI/6}</max_steer>
            <max_steering_angle>${PI/6}</max_steering_angle>
            <max_speed>10</max_speed>
            <min_speed>-1</min_speed>
            <left_steering_pid_gain>10000 0 1</left_steering_pid_gain>
            <left_steering_i_range>0 0</left_steering_i_range>
            <right_steering_pid_gain>10000 0 1</right_steering_pid_gain>
            <right_steering_i_range>0 0</right_steering_i_range>
            <linear_velocity_pid_gain>100 0 1</linear_velocity_pid_gain>
            <linear_velocity_i_range>0 0</linear_velocity_i_range>
            <publish_odom>true</publish_odom>
            <publish_odom_tf>true</publish_odom_tf>
            <publish_wheel_tf>true</publish_wheel_tf>
            <publish_distance>true</publish_distance>
            <odometry_frame>world</odometry_frame>
            <robot_base_frame>base_footprint</robot_base_frame>
        </plugin> 
    </gazebo>
  </xacro:macro>

</robot>
